### PR TITLE
CI: Remove publish Workflow, does not yet implement "gem cert" usage

### PR DESCRIPTION
**Pull request by olleolleolle**
Closes: n/a

# Goal

Cleanup of CI configuration.

This change removes the Publish Workflow, to match the actually-used release process.

# Approach
1. Read each Workflow.
2. ~See that Bundler is not used.~
3. Learn that this Workflow is not used.

Signed-off-by: Olle Jonsson <olle.jonsson@gmail.com>

### CODE REVIEW

**Comment by ivanoblomov** [comment]
Note I was never able to get this working, but it occurs to me now that since I started signing the gem (to comply with the [Secure release](https://bestpractices.coreinfrastructure.org/en/projects/92?criteria_level=1#security) requirement of Best Practices, publishing using the workflow will no longer work anyway (since we can't commit private keys).

**Comment by olleolleolle** [comment]
@ivanoblomov Cool, with that in mind, would you want me to drop this Workflow in this PR, just removing it?

**Comment by ivanoblomov** [comment]
Yeah, sounds good. Just wanted to run it by you first in case I was overlooking an option.

**Comment by olleolleolle** [comment]
@ivanoblomov It _may_ be possible to fiddle with the Secrets system in GitHub, and placing a valid `gem cert` in there, etc etc. If we are not doing that now, it would be more clear to the reader that the release process is not using the CI Workflow, and remove this file

**Review by ivanoblomov — APPROVED** [review]

**Pull request merged**
